name: Upload Artifacts - iOS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy website
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pages
          path: docs
          retention-days: 3
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          branch: main
          folder: docs