name: Upload Artifacts - iOS
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: Deploy website
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xcov_output
          path: .
